feat(628): Added a translation check to the pipeline to see if there are any unwanted changes, l10n needs to be executed locally

diff --git a/.github/workflows/flutter_test.yml b/.github/workflows/flutter_test.yml
--- a/.github/workflows/flutter_test.yml
+++ b/.github/workflows/flutter_test.yml
@@ -29,3 +29,10 @@ jobs:
         uses: bluefireteam/melos-action@v3
       - name: Run Flutter Analyze
         run: melos exec -- flutter analyze --no-fatal-infos --no-fatal-warnings
+      - name: Translation Check
+        run: |
+          melos run l10n --no-select
+          # Stage changes so git diff includes newly created files
+          git add -A
+          # Fail if there are any changes in the staged area
+          git diff --staged --exit-code || (echo "Error: Localization files are out of sync. Run 'melos run l10n' locally and commit the changes." && exit 1)
